services:
  web:
    build: .
    volumes:
      - ./django_apps:/web-app-base/django_apps
      - ./staticfiles:/web-app-base/staticfiles
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/web-app-base
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./staticfiles:/usr/share/nginx/html/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_data_app_name:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data_app_name: