services:
  web:
    build: .
    volumes:
      - ./steesh_app:/it-security-steesh/steesh_app
      - ./staticfiles:/it-security-steesh/staticfiles
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/it-security-steesh
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build:
      context: .
      target: nginx_stage
    volumes:
      - ./staticfiles:/usr/share/nginx/html/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_data_steesh:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data_steesh: